# azure-pipelines.yml
trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Faz o checkout do código do repositório GitHub
  - checkout: self

  # Instalar JDK 11 diretamente usando script
  - script: |
      sudo apt-get install -y openjdk-11-jdk
      java -version  # Verificar se o JDK foi instalado corretamente
    displayName: 'Instalar JDK 11'

  # Build do projeto com Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      options: '-B'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  # Publicar cobertura de código usando JaCoCo
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: 'target/site/jacoco/jacoco.xml'
      reportDirectory: 'target/site/jacoco'
      failIfCoverageEmpty: true

