services:
  db:
    container_name: mysqlvini
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROFILE=dev
      - DATABASE_URL=jdbc:mysql://bd-fiap-safecoleta-dev.mysql.database.azure.com:3306/api?createDatabaseIfNotExist=true
      - DATABASE_USER=vinicius
      - DATABASE_PWD=Rootroot#*
